grafana:
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL

prometheus:
  prometheusSpec:
    retention: 2d
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true
